//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Data_Pingdom_Check> Data_Pingdom_Check { get; set; }
        public virtual DbSet<Data_Pingdom_Check_SummaryPerformance> Data_Pingdom_Check_SummaryPerformance { get; set; }
        public virtual DbSet<Report_Clients> Report_Clients { get; set; }
        public virtual DbSet<Report_ClientSites> Report_ClientSites { get; set; }
        public virtual DbSet<Report_Reports> Report_Reports { get; set; }
        public virtual DbSet<ReportData_Pingdom> ReportData_Pingdom { get; set; }
        public virtual DbSet<AutomationReport_Scheduler> AutomationReport_Scheduler { get; set; }
        public virtual DbSet<Data_JiraServiceDesk> Data_JiraServiceDesk { get; set; }
        public virtual DbSet<Report_ClientJiraServiceDesks> Report_ClientJiraServiceDesks { get; set; }
        public virtual DbSet<ReportData_JiraServiceDesk> ReportData_JiraServiceDesk { get; set; }
        public virtual DbSet<Report_CustomContent> Report_CustomContent { get; set; }
        public virtual DbSet<Data_PageSpeedInsights> Data_PageSpeedInsights { get; set; }
        public virtual DbSet<ReportData_PageSpeedInsights> ReportData_PageSpeedInsights { get; set; }
        public virtual DbSet<Data_GoogleAnalytic> Data_GoogleAnalytic { get; set; }
        public virtual DbSet<Data_GoogleSearch> Data_GoogleSearch { get; set; }
        public virtual DbSet<ReportData_GoogleSearch> ReportData_GoogleSearch { get; set; }
        public virtual DbSet<ReportData_GoogleAnalytic> ReportData_GoogleAnalytic { get; set; }
        public virtual DbSet<Data_GoogleSearch_Detail> Data_GoogleSearch_Detail { get; set; }
        public virtual DbSet<Recommendation_Bank> Recommendation_Bank { get; set; }
        public virtual DbSet<Release_Milestone> Release_Milestone { get; set; }
        public virtual DbSet<Data_GoogleSearch_Sitemap> Data_GoogleSearch_Sitemap { get; set; }
        public virtual DbSet<ReportData_GoogleSearch_Sitemap> ReportData_GoogleSearch_Sitemap { get; set; }
        public virtual DbSet<ReportData_ScreamingFrog> ReportData_ScreamingFrog { get; set; }
        public virtual DbSet<ReportSubscription> ReportSubscriptions { get; set; }
        public virtual DbSet<Dynomapper> Dynomappers { get; set; }
        public virtual DbSet<ReportData_Dynomapper> ReportData_Dynomapper { get; set; }
    }
}
