//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomationReport_Scheduler
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<int> ExecutionType { get; set; }
        public string ExecutionExpression { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsHourly { get; set; }
        public Nullable<int> HourlyEveryHour { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<bool> DailyEveryDay { get; set; }
        public Nullable<bool> DailyEveryWeekDay { get; set; }
        public Nullable<bool> IsWeekly { get; set; }
        public string WeeklyDays { get; set; }
        public Nullable<int> StartAtHour { get; set; }
        public Nullable<int> StartAtMinute { get; set; }
        public string ExecutionTool { get; set; }
        public Nullable<int> DailyEveryDayNumber { get; set; }
    }
}
