//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Pingdom_Check
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data_Pingdom_Check()
        {
            this.Data_Pingdom_Check_SummaryPerformance = new HashSet<Data_Pingdom_Check_SummaryPerformance>();
            this.ReportData_Pingdom = new HashSet<ReportData_Pingdom>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string HostName { get; set; }
        public Nullable<long> LastTestTimeUtc { get; set; }
        public string Json { get; set; }
        public Nullable<System.DateTime> CrawledTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_Pingdom_Check_SummaryPerformance> Data_Pingdom_Check_SummaryPerformance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_Pingdom> ReportData_Pingdom { get; set; }
    }
}
