//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GoogleSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data_GoogleSearch()
        {
            this.Data_GoogleSearch_Detail = new HashSet<Data_GoogleSearch_Detail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClientSiteId { get; set; }
        public string Json { get; set; }
        public Nullable<long> DataTimeUtc { get; set; }
        public Nullable<System.DateTime> CrawledTimestamp { get; set; }
    
        public virtual Report_ClientSites Report_ClientSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_GoogleSearch_Detail> Data_GoogleSearch_Detail { get; set; }
    }
}
