//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation_Bank
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ReportSection { get; set; }
        public string Rule { get; set; }
        public string Recommendation { get; set; }
        public string ReportProperty { get; set; }
        public string RuleSql { get; set; }
    }
}
