//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release_Milestone
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClientSiteId { get; set; }
        public string ReleaseVersion { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Description { get; set; }
    
        public virtual Report_ClientSites Report_ClientSites { get; set; }
    }
}
