//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_Reports()
        {
            this.Report_CustomContent = new HashSet<Report_CustomContent>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClientSiteId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ToolIds { get; set; }
        public string ReportName { get; set; }
    
        public virtual Report_ClientSites Report_ClientSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_CustomContent> Report_CustomContent { get; set; }
    }
}
