//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_ClientSites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_ClientSites()
        {
            this.Report_Reports = new HashSet<Report_Reports>();
            this.Data_PageSpeedInsights = new HashSet<Data_PageSpeedInsights>();
            this.ReportData_PageSpeedInsights = new HashSet<ReportData_PageSpeedInsights>();
            this.Data_GoogleAnalytic = new HashSet<Data_GoogleAnalytic>();
            this.Data_GoogleSearch = new HashSet<Data_GoogleSearch>();
            this.ReportData_GoogleSearch = new HashSet<ReportData_GoogleSearch>();
            this.ReportData_GoogleAnalytic = new HashSet<ReportData_GoogleAnalytic>();
            this.Release_Milestone = new HashSet<Release_Milestone>();
            this.Data_GoogleSearch_Sitemap = new HashSet<Data_GoogleSearch_Sitemap>();
            this.ReportData_GoogleSearch_Sitemap = new HashSet<ReportData_GoogleSearch_Sitemap>();
            this.ReportData_ScreamingFrog = new HashSet<ReportData_ScreamingFrog>();
            this.Dynomappers = new HashSet<Dynomapper>();
            this.ReportData_Dynomapper = new HashSet<ReportData_Dynomapper>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LogoUrl { get; set; }
        public string SiteUrl { get; set; }
        public string CrawlerConfig { get; set; }
        public string BrandName { get; set; }
    
        public virtual Report_Clients Report_Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_Reports> Report_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_PageSpeedInsights> Data_PageSpeedInsights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_PageSpeedInsights> ReportData_PageSpeedInsights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_GoogleAnalytic> Data_GoogleAnalytic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_GoogleSearch> Data_GoogleSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_GoogleSearch> ReportData_GoogleSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_GoogleAnalytic> ReportData_GoogleAnalytic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Release_Milestone> Release_Milestone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_GoogleSearch_Sitemap> Data_GoogleSearch_Sitemap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_GoogleSearch_Sitemap> ReportData_GoogleSearch_Sitemap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_ScreamingFrog> ReportData_ScreamingFrog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dynomapper> Dynomappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_Dynomapper> ReportData_Dynomapper { get; set; }
    }
}
