//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_ClientJiraServiceDesks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_ClientJiraServiceDesks()
        {
            this.ReportData_JiraServiceDesk = new HashSet<ReportData_JiraServiceDesk>();
        }
    
        public System.Guid Id { get; set; }
        public string ServiceDeskUrl { get; set; }
        public string ProjectKey { get; set; }
        public string OrganizationName { get; set; }
        public string OrgNameForProjectIfNotProvided { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData_JiraServiceDesk> ReportData_JiraServiceDesk { get; set; }
    }
}
