//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSubscription
    {
        public System.Guid Id { get; set; }
        public System.Guid ReportId { get; set; }
        public string ReceiverEmails { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> SubscribedByUser { get; set; }
        public Nullable<bool> IsHourly { get; set; }
        public Nullable<int> HourlyEveryHour { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<bool> DailyEveryDay { get; set; }
        public Nullable<bool> DailyEveryWeekDay { get; set; }
        public Nullable<int> DailyEveryDayNumber { get; set; }
        public Nullable<bool> IsWeekly { get; set; }
        public string WeeklyDays { get; set; }
        public Nullable<int> StartAtHour { get; set; }
        public Nullable<int> StartAtMinute { get; set; }
        public string SubscribedUser { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<int> MonthlyDay { get; set; }
        public Nullable<int> MonthlyEveryMonth { get; set; }
    }
}
