//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_Clients()
        {
            this.Report_ClientSites = new HashSet<Report_ClientSites>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LogoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_ClientSites> Report_ClientSites { get; set; }
    }
}
