//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.ReportAutomation.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_CustomContent
    {
        public System.Guid Id { get; set; }
        public System.Guid ReportId { get; set; }
        public int ReportDays { get; set; }
        public long ReportTo { get; set; }
        public string CustomReportContent { get; set; }
        public int UnderReportSection { get; set; }
    
        public virtual Report_Reports Report_Reports { get; set; }
    }
}
